### ISSUE TITLE
Getting the documentation from OAS files in to the proto

### ISSUE THREAD

**Issue by spacedsweden** [google/gnostic-grpc#32]
Hey

Is it possible to get the description and summary text into the generated proto file?

**Comment by LorenzHW** [comment]
Hi Christian,

Yes, I think that is possible, though tricky to implement. gnostic-grpc essentially creates a bunch of [descriptors](https://godoc.org/github.com/golang/protobuf/descriptor) and then uses [protoreflect](https://github.com/jhump/protoreflect/) to generate the proto file from these descriptors. I think one possible approach would be to fill the [SourceCodeInfo](https://github.com/protocolbuffers/protobuf-go/blob/master/types/descriptorpb/descriptor.pb.go#L2473).

This could be accomplished the following way:
- After gnostic-grpc is done generating the proto file, protoc could be used to regenerate the descriptor with the following command:
``
protoc --include_source_info --descriptor_set_out=output.descr generated_file_by_gnosticgrpc.proto
``
- Then unmarshal output.descr to a `FileDescriptorSet`. The result of this is that `SourceCodeInfo` is now partially filled.
- Now the tricky part is to map the description and summary (that are already partially included in the surface model) to the correct [SourceCodeInfo_Location](https://github.com/protocolbuffers/protobuf-go/blob/master/types/descriptorpb/descriptor.pb.go#L2857) where we could finally add the description or summary text as `LeadingComments`.
- Then the modified descriptor should result in a proto file with comments.

@noahdietz Do you think that would work?

**Comment by LorenzHW** [comment]
Actually the approach above is a bit too complicated. This can be done easier. See PR.
