### ISSUE TITLE
Any plans on releasing with latest master?

### ISSUE THREAD

**Issue by nerixim** [google/gnostic-grpc#35]
Hi 👋 and thanks for your work. 
There were several improvements since [v0.1.0](https://pkg.go.dev/github.com/googleapis/gnostic-grpc). Could you make a release with the latest version?

Regards

**Comment by LorenzHW** [comment]
Hi 👋 

sure. I just released [v0.1.1](https://github.com/google/gnostic-grpc/releases/tag/v0.1.1).

Greetings
