### ISSUE TITLE
Broken proto on fields with numbers or hyphens

### ISSUE THREAD

**Issue by ChepChaf** [google/gnostic-grpc#79]
When parsing an enum that has fields which start in a number it generates a broken proto file.

```
enum:
  - 5FOO_BAR 
```
translates to
```
enum Value {
    5FOO_BAR = 0;
}
```
which is not a valid field.

Something like:

```
enum:
  - FOO-BAR
```

Get parsed as
```
enum Value {
  FOO-BAR = 0;
}
```

message names that starts with numbers have the same problem:
```
properties:
  5FooBar:
    ...
```

```
message 5FooBar {
  ...
```

## Possible fix

Escape some characters to underscores or add undescore at the beggining of enum fields to make them valid

**Comment by LorenzHW** [comment]
@TylerGillson Hi, yeah I still I have an eye on it. If you want I can guide you through the change I don't think it is that much effort. I don't find the time right now tho. Is it critical to you?

**Comment by TylerGillson** [comment]
@LorenzHW Awesome! Is @ChepChaf's solution not acceptable? If it is I was just hoping that you might merge it.

However I did notice that it is breaking some of your tests. Happy to make changes if you can give me some pointers!

**Comment by LorenzHW** [comment]
@TylerGillson Oh sorry. I didn't see that someone contributed TBH. Gotta turn on GitHub notifications again for this repo. But usually @LorenzHW I will notice. Anyways..

I will take a look at this repository again on the upcoming weekend :)

**Comment by LorenzHW** [comment]
I just merged [this](https://github.com/google/gnostic-grpc/pull/80). Thanks for the contribution.
